// <auto-generated />
using ChekingSys.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChekingSys.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210323153756_AddCategoryToDatabase")]
    partial class AddCategoryToDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ChekingSys.Models.Worker", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HolidaysВeekends")
                        .HasColumnType("int");

                    b.Property<int>("Illness")
                        .HasColumnType("int");

                    b.Property<string>("M1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M14")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M16")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M17")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M18")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M19")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M20")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M21")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M22")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M23")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M24")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M25")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M26")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M27")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M28")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M29")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M30")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M31")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonthlyRate")
                        .HasColumnType("int");

                    b.Property<int>("Motherhood")
                        .HasColumnType("int");

                    b.Property<string>("NamеSurname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Overtime")
                        .HasColumnType("float");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegularLeave")
                        .HasColumnType("int");

                    b.Property<int>("Shift1")
                        .HasColumnType("int");

                    b.Property<int>("Shift2")
                        .HasColumnType("int");

                    b.Property<int>("UnpaidLeave")
                        .HasColumnType("int");

                    b.Property<double>("workedays")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("Workers");
                });
#pragma warning restore 612, 618
        }
    }
}
