// <auto-generated />
using ChekingSys.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChekingSys.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210317180816_AddBlogCreatedTimestamp")]
    partial class AddBlogCreatedTimestamp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ChekingSys.Models.Worker", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Illness")
                        .HasColumnType("int");

                    b.Property<string>("March1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("March10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("March11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("March12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("March13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("March14")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("March15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("March16")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("March17")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("March18")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("March19")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("March2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("March20")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("March21")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("March22")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("March23")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("March24")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("March25")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("March26")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("March27")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("March28")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("March29")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("March3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("March30")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("March31")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("March4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("March5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("March6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("March7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("March8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("March9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonthlyRate")
                        .HasColumnType("int");

                    b.Property<int>("Motherhood")
                        .HasColumnType("int");

                    b.Property<string>("NamеSurname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Overtime")
                        .HasColumnType("float");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegularLeave")
                        .HasColumnType("int");

                    b.Property<int>("Shift1")
                        .HasColumnType("int");

                    b.Property<int>("Shift2")
                        .HasColumnType("int");

                    b.Property<int>("UnpaidLeave")
                        .HasColumnType("int");

                    b.Property<double>("workedays")
                        .HasColumnType("float");

                    b.Property<int>("ХolidaysВeekends")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Workers");
                });
#pragma warning restore 612, 618
        }
    }
}
